In [1]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import BatchNormalization

In [2]:
# Инициализация входного тензора
x = np.ones((5, 2, 3,))

# Инициализация слоя
layer = BatchNormalization(epsilon=1e-8,
                           gamma_initializer='ones', # По умолчанию
                           beta_initializer='zeros', # По умолчанию
                           moving_mean_initializer='zeros', # По умолчанию
                           moving_variance_initializer='ones', # По умолчанию
                           )

# Инициализируем веса
layer(x)

# Вытащим веса
w = np.array(layer.get_weights())

print('Входной тензор:')
print(x)

# Отобразим веса
print('Все веса:\n', str(w))
print('Форма:', w.shape)

Входной тензор:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
Все веса:
 [[1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]]
Форма: (4, 3)


In [3]:
print('Выход слоя (режим теста):')
print(layer(x)) # training=False

print('Выход слоя (режим тренировки):')
print(layer(x, training=True))

Выход слоя (режим теста):
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(5, 2, 3), dtype=float32)
Выход слоя (режим тренировки):
tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(5, 2, 3), dtype=float32)


In [4]:
print('Выход слоя (режим теста):')
print(layer(x)) # training=False

Выход слоя (режим теста):
tf.Tensor(
[[[0.9949874 0.9949874 0.9949874]
  [0.9949874 0.9949874 0.9949874]]

 [[0.9949874 0.9949874 0.9949874]
  [0.9949874 0.9949874 0.9949874]]

 [[0.9949874 0.9949874 0.9949874]
  [0.9949874 0.9949874 0.9949874]]

 [[0.9949874 0.9949874 0.9949874]
  [0.9949874 0.9949874 0.9949874]]

 [[0.9949874 0.9949874 0.9949874]
  [0.9949874 0.9949874 0.9949874]]], shape=(5, 2, 3), dtype=float32)


In [5]:
print('\nПараметры:')
print('w[0] =', w[0], '- gamma')
print('w[1] =', w[1], '- beta')
print('w[2] =', w[2], '- moving_mean')
print('w[3] =', w[3], '- moving_variance')


Параметры:
w[0] = [1. 1. 1.] - gamma
w[1] = [0. 0. 0.] - beta
w[2] = [0. 0. 0.] - moving_mean
w[3] = [1. 1. 1.] - moving_variance


In [6]:
new_w = w.copy()

# Изменение значения beta, соответствующего каналу 1
new_w[1][1] = 10

# Устанавка новых весов
layer.set_weights(new_w)

# Проверка результата
new_w = np.array(layer.get_weights())

print('Новые веса:')
print(new_w)

print('Выход слоя:')
print(layer(x, training=True))

Новые веса:
[[ 1.  1.  1.]
 [ 0. 10.  0.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
Выход слоя:
tf.Tensor(
[[[ 0. 10.  0.]
  [ 0. 10.  0.]]

 [[ 0. 10.  0.]
  [ 0. 10.  0.]]

 [[ 0. 10.  0.]
  [ 0. 10.  0.]]

 [[ 0. 10.  0.]
  [ 0. 10.  0.]]

 [[ 0. 10.  0.]
  [ 0. 10.  0.]]], shape=(5, 2, 3), dtype=float32)


In [7]:
print('epsilon:', layer.epsilon)

epsilon: 1e-08
