In [1]:
import tensorflow as tf

In [3]:
import numpy as np
from tensorflow.keras.layers import Dropout

# Входной тензор
X = np.ones((5, 2))

# Создание и вызов слоя в тестовом режиме
Dropout(0.2)(X)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

In [4]:
# Задание состояния
tf.random.set_seed(3)

# Создание и вызов слоя в тренировочном режиме
Dropout(0.2)(X, training=True)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1.25, 0.  ],
       [1.25, 1.25],
       [1.25, 1.25],
       [1.25, 1.25],
       [1.25, 1.25]], dtype=float32)>

In [5]:
import numpy as np
from keras.layers import Dropout

In [6]:
# Инициализация входной матрицы
X = np.ones((5, 2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
# Создание слоя Dropout с параметром 0.2
dropout_layer = Dropout(rate=0.5)

In [8]:
dropout_layer(X, training=True)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [2., 2.],
       [2., 0.],
       [2., 2.]], dtype=float32)>